name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy # Changes in 'deploy' branch will be published to GitHub Pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build site
        run: |
          make tidy
          make run
          # Ensure static files are in 'public'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
